[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
via_ir = true
optimizer_runs = 200
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "@somnia-chain/reactivity-contracts/=node_modules/@somnia-chain/reactivity-contracts/",
]

[profile.default.fuzz]
runs = 512
